### ISSUE TITLE
Why mandate the Azure SPN login?

### ISSUE THREAD

**Issue by arvindshmicrosoft** [Azure/sql-action#10]
Hello team, this action is very useful, however the requirement to have a SPN which is used to adjust the firewall rules is a bit restrictive. In many cases, the target logical Azure SQL server already exists and has firewall rules adjusted already, or maybe the customer is running with self-hosted runner within a private VNET etc. In those cases, this step of mandating the Azure login is functionally not needed. Functionally, an ops person should be able to just specify the connection string and theoretically be able to specify that the firewall rules adjustment are not needed. Eager to know your thoughts on this.

**Comment by N-Usha** [comment]
Thanks so much for the feedback @arvindshmicrosoft. Closing the issue as we addressed the feedback by updating the documentation.

**Comment by jonthenerd** [comment]
The documentation has been updated, but the action still requires the information. No updates were made to the code in the repo, just the readme. Can this be addressed?
