### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by lucasteles** [Azure/sql-action#11]
Any plans to support linux host?

**Comment by N-Usha** [comment]
@lucasteles - Can you please explain your request further? Linux runners are supported for GH Actions. Please let us know if you are facing any specific issues.

**Comment by lucasteles** [comment]
@N-Usha i tried to run this action in a Linux host and it gave me an error

 `This action is not supported on a non-windows environment.`

**Comment by godefroi** [comment]
I would also love to be able to run this on a Linux host; I believe SQLPACKAGE is available for Linux, so it *should* be possible?

**Comment by ozcan-ozkaya** [comment]
I'm also interested to run this action on a Linux host, is there any information when will be implemented?

**Comment by dzsquared** [comment]
Work for supporting SqlPackage in the Linux pipeline environment is in progress and should be complete within a few months at the most - once this is complete I will follow up on this thread.

**Comment by tesar-tech** [comment]
Do we have any alternatives?

**Comment by fnmarquez** [comment]
I need this!

**Comment by johndowns** [comment]
I see PR #50 was merged. Is there an ETA for when this will be published and ready to use?

**Comment by johndowns** [comment]
@N-Usha Are you able to provide an update on the rollout of this task? Thanks!

**Comment by dzsquared** [comment]
@johndowns - there were numerous CI issues in the repo that we've been resolving before tagging a new release. Should be very soon (days) at this time.

**Comment by dzsquared** [comment]
Now available in v1.1 
https://github.com/Azure/sql-action/releases/tag/v1.1
