### ISSUE TITLE
Azure Login is still required, despite closed issue.

### ISSUE THREAD

**Issue by jonthenerd** [Azure/sql-action#14]
The documentation has been updated, but the action still requires the information. No updates were made to the code in the repo, just the readme. Can this be addressed?

_Originally posted by @jonthenerd in https://github.com/Azure/sql-action/issues/10#issuecomment-651405162_

If it is supported to not have to supply Azure Login credentials, an example of how to do so (as just omitting it doesn't work) would be much appreciated.

**Comment by aksm-ms** [comment]
Issue is fixed in PR. Please let me know if there are any other queries.

**Comment by aksm-ms** [comment]
@jonthenerd can you please confirm if you are able to run your workflow without issues?

**Comment by aksm-ms** [comment]
Closing the issue since its fixed in PR. Please reopen if you have further queries.
