### ISSUE TITLE
Action does not work when connection string server name contains "tcp:"

### ISSUE THREAD

**Issue by saasaTom** [Azure/sql-action#143]
This action fails when the connection string contains a server name with "TCP" e.g. `Server=tcp: MY_SERVER`.

It fails when creating firewall rules due to filtering azure resources based off the Server value (including the text "tcp:". i.e. it looks for an azure resource with the name `tcp: MY_SERVER`

The error is thrown:
`Unable to get details of SQL server tcp: MY_SERVER. Sql server 'tcp: MY_SERVER' was not found in the subscription.`

https://github.com/Azure/sql-action/blob/aacc6bc593bb80d5cfc0daf0c2ca523b9b133ddb/src/AzureSqlResourceManager.ts#L133

If no firewall is required, the connection works fine.

This should also be able to work using non-standard ports. i.e. `Server=MY_SERVER,MY_PORT`

**Comment by dzsquared** [comment]
In version 2.1 we've added more debug logging- will you try it with debug logging enabled to see if more information is shown? 
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging
