### ISSUE TITLE
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.

### ISSUE THREAD

**Issue by vijayshinva** [Azure/sql-action#149]
On a self-hosted Windows(OS Build 20348.1129)  runner get the following error 

`Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.`

![image](https://user-images.githubusercontent.com/16094361/200126631-6fe6660e-0587-4232-82e1-aadf6371bf10.png)

Action Step

![image](https://user-images.githubusercontent.com/16094361/200126696-494f8c60-2fad-441c-95e2-eae2de4dea75.png)

**Comment by pnoshell** [comment]
pretty much the same error with self-hosted runner too.

**Comment by catoa** [comment]
Any updates on this? I'm also experiencing this issue on v2.

**Comment by dzsquared** [comment]
Does running the action with debug logs enabled give further details? 
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

**Comment by vijayshinva** [comment]
Logs with Debug Logging. The issue exists with sql-action@v2.1 as well.

![image](https://user-images.githubusercontent.com/16094361/221482115-27006ba1-6a5c-4e17-8a42-97bd0b861038.png)

**Comment by dzsquared** [comment]
Fix now available in v2.1.1 https://github.com/Azure/sql-action/releases/tag/v2.1.1
thank you!
