### ISSUE TITLE
SQL Managed Instance

### ISSUE THREAD

**Issue by shanchatterjee** [Azure/sql-action#161]
Does this action support SQL Managed Instance deployment ? 

I followed every step to connect to Azure, and deploy my database which is in SQL MI, only to end up in message:

Unable to get details of SQL server <server>. No SQL servers were found in the subscription.

Got a post where people from Microsoft confirms this action is only limited to Azure SQL.

https://learn.microsoft.com/en-us/answers/questions/1155045/github-deploy-actions-for-azure-sql-managed-instan?page=1&orderBy=Helpful&comment=answer-1155167#newest-answer-comment

Any help on SQL Managed Instance deployment will be greatly appreciated.

**Comment by dzsquared** [comment]
The message you received suggests that when the action tried to connect to your MI database, it wasn't able to connect - so it tried to update firewall rules for the SQLDB.
While there isn't anything in this action that keeps it from supporting MI, the networking for your server and GitHub workflow does need to be configured to allow connectivity.

https://learn.microsoft.com/azure/azure-sql/managed-instance/connectivity-architecture-overview

Are you using sql-action from a GitHub hosted workflow? If so, is the endpoint for the connection string accessible from all other Azure resources?

_Additional debug logging is available as well: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging_

**Comment by dzsquared** [comment]
@shanchatterjee were you able to establish connectivity with the public endpoint for your SQL MI instance or host the runner on a VM in the SQL MI vnet?

**Comment by shanchatterjee** [comment]
Unfortunately no. We have run out of all our ideas. Got Microsoft involved now.

**Comment by shanchatterjee** [comment]
We managed to get a connectivity to Azure SQL MI by installing a self-hosted runner in a VM in the SQL MI VNet.
Thank you for all your help and patience. We had a successful deployment.

**Comment by dzsquared** [comment]
Fantastic, I'm so glad it worked out in your isolated environment.
Were there takeaways or friction points in setting up the self-hosted runner that you can share?  I'd like to add docs on this for future users if it might be helpful. 😄

**Comment by shanchatterjee** [comment]
Sure, 

We had to additionally install the following on the VM.

1) Install Visual Studio with Data Tools Workload. The application needs vswhere executable
https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2022

2) Open Powershell and check if Azure CLI components are installed. If not, install from:
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli

3) Install SQL Package
https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15&viewFallbackFrom=sql-server-ver17

4) Install Git:
https://git-scm.com/download/win

4) Also, I had to additionally add these code to the workflow:

      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Add safe directory
        run: git config --global --add safe.directory *
