### ISSUE TITLE
Unable to pass variable from sql-action to dacpac

### ISSUE THREAD

**Issue by dwinshipIdentifi** [Azure/sql-action#179]
Github Action 
- uses: Azure/sql-action@v2.2
      with:        
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './database-build/bin/Release/net7.0/database-build.dacpac'
        action: 'publish'
        arguments: '/p:DropObjectsNotInSource=true /p:BlockOnPossibleDataLoss=false /v:RELEASEVERSION="1.0.0"'

Dacpac
UPDATE [dbo].[Settings] SET [Version] = '$(RELEASEVERSION)'
GO

Error message 
*** The following SqlCmd variables are not defined in the target scripts: RELEASEVERSION.

**Comment by dzsquared** [comment]
Just checking that the variable is also defined in the .sqlproj file used to create the dacpac.  A sample of what that would look like is:

```xml
<ItemGroup>
    <SqlCmdVariable Include="RELEASEVERSION">
      <Value>$(SqlCmdVar__1)</Value>
    </SqlCmdVariable>
  </ItemGroup>
```

If you're able to share the dacpac for further troubleshooting, please reach out to me at drskwier@microsoft.com

**Comment by dzsquared** [comment]
closing stale issues, please let us know if you continue to experience this issue
