### ISSUE TITLE
SSDT error while deploying it from GitHub self hosted runner

### ISSUE THREAD

**Issue by ramesh82** [Azure/sql-action#180]
Hi all,

I am getting the below error when publishing dacpac from self hosted runner.

`Error: There was an error when attempting to execute the process 'sqlpackage'. This may indicate the process failed to start. Error: spawn sqlpackage ENOENT`

It would be good to get some assistance on this issue.

**Comment by dzsquared** [comment]
Is sqlpackage installed on your runner image?  Do you know what path sqlpackage is installed on?

**Comment by G0rdonHill** [comment]
I'm having this issue on a private runner docker image. Docker image installs sqlpackage at `~/sqlpackage` and adds it to PATH. Another job in the workflow is able to use it. Any assistance would be great!

**Comment by stiTMetcalfe** [comment]
Had same issue - https://github.com/Azure/sql-action/issues/187
