### ISSUE TITLE
Getting error Failed to add firewall rule error during sql script execution using GitHub Hosted Runner

### ISSUE THREAD

**Issue by fmouraine** [Azure/sql-action#181]
Here my github action I use:

-----------------------------
- name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets. client-id }}
          subscription-id: ${{ secrets.subscription-id }}
          tenant-id: ${{ secrets.tenant-id }}

- name: Init Mssql db-user
      uses: azure/sql-action@v2.2
      with:        
      connection-string: "Server=myserver.database.windows.net,1433;Database=mydb;Authentication=Active Directory Default"
      path: './mssql/scripts/db-init-user.sql'

------------------------------
If I launch it on ubuntu-latest (public runner), it works fine
If I launch it on an private runner (located in the same vnet as the sql server and sql server has a private endpoint), I have an authentification error (the github action return a failed to add firewall rules but in debug mode I can see authentification error)

It seems that the Github action Azure/sql-action does not managed correctly the authentification with AAD federation (when not using a public github runner). This analysis has been confirmed by Azure support

**Comment by catoa** [comment]
@fmouraine this sounds similar to the error that I've encountered while trying to deploy to a SQL Managed Instance. This is the error that I see in the GHA workflow:
```
Error: Failed to add firewall rule. Unable to detect client IP Address. lookup <db-name>.database.windows.net: no such host
```
