### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by johannesnormannjensen** [Azure/sql-action#183]
Trying to publish a dacpac but I keep getting this error:

```
No usable version of libssl was found
Error: The process 'sqlpackage' failed with exit code null
```

My action-runner in running Ubuntu 22.04 with `libunwind8` + `libssl-dev` is installed as required per the sqlpackage documentation: https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16 

What am I doing wrong?

**Comment by zijchen** [comment]
@johannesnormannjensen The dependencies of sqlpackage come from .NET 6, the recommendation is to install the .NET 6 SDK with a package manager. You can refer to the .NET SDK docs for full list of dependencies: https://learn.microsoft.com/dotnet/core/install/linux-ubuntu-2204#dependencies
