### ISSUE TITLE
Error: There was an error when attempting to execute the process 'sqlpackage'.

### ISSUE THREAD

**Issue by stiTMetcalfe** [Azure/sql-action#187]
This is the error that I get with running azure/sql-action@v2.2 and following the documentation exactly as stated. https://github.com/Azure/sql-action#azure-credentials-for-login-quickstart

Error: There was an error when attempting to execute the process 'sqlpackage'. This may indicate the process failed to start. Error: spawn sqlpackage ENOENT

I have validated that I can get a sql script to run using azure/sql-action@v2.2 and it connects to the database and returns the results to the runner as I was expecting. (path: 'Test.sql' action: 'Script')

Connection to an Azure PaaS DB using the Azure/login@v1.4.6 - https://github.com/Azure/sql-action#azure-credentials-for-login-quickstart

Appreciate you looking into this

**Comment by Blinq-SanderBlom** [comment]
> 

This is probably and issue with the runner not having the microsoft.sqlpackage installed. If you have Linux runner you can install it with this command ```dotnet tool install --tool-path /usr/local/bin/ microsoft.sqlpackage```. You will also need to have .NET 6 SDK installed.

**Comment by stiTMetcalfe** [comment]
I ended up having to do this - echo "/home/runner/sqlpackage/" >> $GITHUB_PATH

**Comment by ashrodan** [comment]
for me it was ensuring the build step runs on the same as the deploy step
build step had the 
```- name: Install SqlPackage
        shell: cmd
        run: dotnet tool install -g microsoft.sqlpackage
        ```
