### ISSUE TITLE
[Security] Use role "SQL Server Contributor" instead of "Contributor"

### ISSUE THREAD

**Issue by FlorentATo** [Azure/sql-action#201]
In order to update the SQL Server firewall, the identity used to authenticate to Azure (using [azure/login](https://github.com/azure/login)) needs to have the following permissions:
- Microsoft.Sql/servers/firewallRules/write
- Microsoft.Sql/servers/firewallRules/delete

Details: https://learn.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftsql

In the spirit of the principle of least privilege, the [documentation](https://github.com/Azure/sql-action/blob/master/CONNECTION.md#azure-active-directory-service-principal-authentication) should be updated to use the role [SQL Server Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#sql-server-contributor) instead of [Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#contributor).

Note: Users looking for further security hardening could also create a [custom Azure role](https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles) with only these two permissions.

**Comment by dzsquared** [comment]
thank you for the notes and opening the PR, taking a look shortly!

**Comment by dzsquared** [comment]
PR merged, docs update
