### ISSUE TITLE
Az login issue

### ISSUE THREAD

**Issue by sekharreddy2772** [Azure/sql-action#216]
Error:1
Done setting cloud: "azurecloud"
Note: Azure/login action also supports OIDC login mechanism. Refer [https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication] for more details.
Attempting Azure CLI login by using service principal with secret...
Error: The subscription of '0b6fcf9a-a18f-47b8-b229-01cde8a03feb' doesn't exist in cloud 'AzureCloud'.

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to [https://github.com/Azure/login#readme] for more information.

Error:2
Attempting Azure CLI login by using service principal with secret...
Error: The subscription of '0b6fcf9a-a18f-47b8-b229-01cde8a03feb' doesn't exist in cloud 'AzureCloud'.

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.

1. Double check if the 'auth-type' is correct. Refer to [https://github.com/Azure/login#readme](https://apc01.safelinks.protection.outlook.com/for more information.
Code: ResourceGroupNotFound
Message: Resource group 'ipssq00rgpprmry' could not be found.

We are getting above 3 error in the workflow,once we re-trigger the same job it's getting successful run without changing anything.

**Comment by dzsquared** [comment]
@sekharreddy2772 - is this error coming from the az-login step of the workflow or the sql-action step?

**Comment by dzsquared** [comment]
Closing this issue until @sekharreddy2772 can clarify which step is throwing the error
