### ISSUE TITLE
Breaking change to arguments in v2.3

### ISSUE THREAD

**Issue by emil-eklund** [Azure/sql-action#235]
We are experiencing some issues since the latest release ([v2.3](https://github.com/Azure/sql-action/releases/tag/v2.3)).
I don't know if this is a bug or intentional, but it seems as if parameters passed are forwarded incorrectly.
  
![image](https://github.com/Azure/sql-action/assets/9718074/e67aa6e1-f1a4-4798-9461-b293f7e8d822)

<details>
<summary>
Logs
</summary

```

with:
    connection-string: Data Source=aimplan-sqlne.database.windows.net; Initial Catalog=I0102; Authentication=Active Directory Default; Encrypt=True; TrustServerCertificate=False;
    path: alter-pbi-user.sql
    arguments: -V11  -b  -v PaddedId="0102" -v PowerBiPassword="***"
  
    skip-firewall-check: false
  env:
    power_bi_password: ***
    padded_id: 0102
tar xj --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/b817[3](https://github.com/aimplan/automation/actions/runs/9841083451/job/27167160648#step:8:3)8fc-779e-4478-a394-31d5f500971e -f /home/runner/work/_temp/4977697e-68fd-48fa-bcd1-684a5a7915f2
sqlcmd -S aimplan-sqlne.database.windows.net,1433 -d I0102 --authentication-method=ActiveDirectoryDefault -i alter-pbi-user.sql -V11 -b -v PaddedId=0102 -v PowerBiPassword=***
Sqlcmd: Error:  Error occurred while opening or operating on file -V[11](https://github.com/aimplan/automation/actions/runs/9841083451/job/27167160648#step:8:12) (Reason: open -V11: no such file or directory).
Error: The process 'sqlcmd' failed with exit code 1
```
</details>

This is the pipeline step which has started to fail:

```yml
    - name: Alter PBI user with new password
      uses: Azure/sql-action@master
      with:
        connection-string: >-
          Data Source=${{ vars.SERVER_NAME }}.database.windows.net;
          Initial Catalog=I${{ env.padded_id }};
          Authentication=Active Directory Default;
          Encrypt=True;
          TrustServerCertificate=False;
        path: alter-pbi-user.sql
        arguments: >
          -V11 
          -b 
          -v PaddedId="${{ env.padded_id }}"
          -v PowerBiPassword="${{ env.power_bi_password }}"
```

I will investigate this further soon, but maybe you already know what's changed.

**Comment by zijchen** [comment]
Hi @emil-eklund What version of sql-action were you using prior to v2.3?

**Comment by dzsquared** [comment]
-V11 is not a valid argument for go-sqlcmd

**Comment by emil-eklund** [comment]
Hi,

@zijchen Seems like we were using `@master`, so I suspect it's the latest release (v2.2.1).

@dzsquared Are you sure? We've been using it for a long time. I think it sets which severity level is fatal to the command. We ha instances in the past where it would continue executing as if all were well, despite fatal errors. 


> Use the following practices to help maximize correctness:

>
>Use -V16 to log any [severity 16 level messages](https://learn.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-error-severities?view=sql-server-ver16#levels-of-severity). Severity 16 messages indicate general errors that can be corrected by the user.

>
>Check the exit code and DOS ERRORLEVEL variable after the process has exited. sqlcmd returns 0 normally, otherwise it sets the ERRORLEVEL as configured by -V. In other words, ERRORLEVEL shouldn't be expected to be the same value as the error number reported from SQL Server. The error number is a SQL Server-specific value corresponding to the system function [@@ERROR](https://learn.microsoft.com/en-us/sql/t-sql/functions/error-transact-sql?view=sql-server-ver16). ERRORLEVEL is a sqlcmd-specific value to indicate why sqlcmd terminated, and its value is influenced by specifying -b command line argument.

>
>Using -V16 in combination with checking the exit code and DOS ERRORLEVEL can help catch errors in automated environments, particularly quality gates before a production release.

**Comment by dzsquared** [comment]
shouldn't it be `-V 11` instead of `-V11`

**Comment by emil-eklund** [comment]
> shouldn't it be `-V 11` instead of `-V11`

Maybe. It would make a lot more sense, but that's not what the documentation said 💁‍♂️
I'll do some testing tomorrow. If that works, then that would be a great solution!!

**Comment by emil-eklund** [comment]
Thank you @dzsquared & @zijchen for jumping on this so quickly.
I tried using "-V 11" as you mentioned, and it is working! 🥳

 I'd love to find out why this stopped working and if it's likely to impact anyone else, but as I'm squeezed for time, I'll just close this ticket.

Once again, thank you for helping! You saved me!

**Comment by emil-eklund** [comment]
Just in case somebody stumbles upon this in the future, we encountered the same issue with another parameter.
If you used something like "-h-1" to remove headers, then this breaks in the same manner. Solution is to use "-h -1" instead.

**Comment by shueybubbles** [comment]
there's a bug in sqlcmd's parsing of arguments that come after `-i filename` 
`-i` can take multiple file names, and the lack of space fools the parser into thinking the argument is a file name instead of an argument.

**Comment by dzsquared** [comment]
@shueybubbles  - did you implement argument parsing without spaces in go-sqlcmd? sql-action uses go-sqlcmd and based on docs I've seen on go-sqlcmd it doesn't support no spaces.
