### ISSUE TITLE
Action does not support AccessToken\ServicePrincipal

### ISSUE THREAD

**Issue by ukphillips-kt** [Azure/sql-action#27]
The current task requires a connection string with a hardcoded user name and password (for internal validation). I would like to request adding the feature to support either AccessToken based connection strings, or directly configuring the task to use service principal credentials to acquire and use the token internally.

**Comment by aksm-ms** [comment]
@ukphillips-kt Is the suggestion to give username, password, server-name, port, etc as individual parameters instead of as a single connection string?

Also can you please elaborate on "AccessToken based connection strings" ? Please attach useful documentation if any.

**Comment by amit-avit** [comment]
Closing due to no response.
