### ISSUE TITLE
Action not accepting multiple sql files or folder (despite being documented)

### ISSUE THREAD

**Issue by abhinaba-chakraborty-by** [Azure/sql-action#28]
As per the documentation [here](https://github.com/Azure/sql-action/blob/master/action.yml):
```
  sql-file:
    description: 'Path to SQL script file. *.sql or a folder to deploy'
```

So we should be able to pass a directory name or pass wildcard like *.sql. But when done so, it fails complaining:
(for wildcard)
```
Error: Muliple files found matching pattern ./abc/xyz/*.sql
```
and , for folder,

```
Error: Invalid sql file path provided as input ./abc/xyz/
```

Is this feature not supported yet? If so, can the documentation please be corrected?

**Comment by aksm-ms** [comment]
@abhinaba-chakraborty-by Currently the action does not support multiple files. I have updated the documentation.

**Comment by abhinaba-chakraborty-by** [comment]
@aksm-ms Ok. Thanks. And also is this action not supported in Linux environment ?? Coz I got the error "This action is not supported on a non-windows environment."

**Comment by aksm-ms** [comment]
@abhinaba-chakraborty-by Currently linux is not supported. There is already an enhancement request tracking this [https://github.com/Azure/sql-action/issues/11](https://github.com/Azure/sql-action/issues/11)

**Comment by joe-schmirler** [comment]
@aksm-ms Multiple files still cannot be ran, despite the readme still has an example of multiple scripts: See '[Deploy SQL scripts to an Azure Database with a temporary firewall rule](https://github.com/Azure/sql-action?tab=readme-ov-file#deploy-sql-scripts-to-an-azure-sql-database-with-a-temporary-firewall-rule)'.
