### ISSUE TITLE
DeployReport support

### ISSUE THREAD

**Issue by kon1180** [Azure/sql-action#55]
Looking at the comment here: https://github.com/Azure/sql-action/blob/master/src/AzureSqlAction.ts#L29
It appears only the publish /action is supported at present. What we would like is for the DeployReport to be supported so as to provide a schema compare given the DDL changes to the target compared to the source dacpac.

I think this addition would greatly lead to adoption as right now you are blind to the net changes that are being made to the target until after those changes are published

**Comment by dzsquared** [comment]
Now supported in v2: https://github.com/Azure/sql-action/releases/tag/v2
