### ISSUE TITLE
Action cannot detect IP address of the runner

### ISSUE THREAD

**Issue by TURQUHARTCOR** [Azure/sql-action#56]
I am running a yaml pipeline with the following job:

![image](https://user-images.githubusercontent.com/85753891/132554031-034dff0a-55a0-4c9a-8865-acd7dd316e43.png)

The login action uses an SPN that has the role **SQL Security Manager**, as per the documentation. 

Expectation: The action would automatically detect the runner IP, add the firewall rule, and remove it afterward.

Error: 
![image](https://user-images.githubusercontent.com/85753891/132552624-1c6b90d9-cda4-403a-8460-c1fb3000c6c5.png)

**Comment by dzsquared** [comment]
hi @TURQUHARTCOR - this error is likely coming from the sqlcmd execution.  To confirm, what type of authentication does your connection string use?
