### ISSUE TITLE
Speed up download time with Webpack

### ISSUE THREAD

**Issue by mayong43111** [Azure/sql-action#69]
I notice that the node_module folder is included in the tag of the publication and need it at run time, but it's very big. I modified to use Webpack to package the project, In my sel-hosted, the Set Up Job step saves 15 seconds. so I recommend using it and remove node_module from tag.

I submitted an RP #68   and I tested it very well

**Comment by dzsquared** [comment]
Added in #74  and released in v1.2
https://github.com/Azure/sql-action/releases/tag/v1.2

thank you!
