### ISSUE TITLE
Failed to add firewall rule - Using self-hosted runner and Deny public access in AzureSQL server

### ISSUE THREAD

**Issue by AlfredyToro** [Azure/sql-action#88]
I have an error when deploying a bacpac from a self hosted runner...I have a sql server but denying public access in the sql server firewall options (obviously this disables the option to add any rule by runner ip)

How could I deploy a bacpac from a self hosted runner to a server that only uses private endpoint. I need to automate this action.

**_"Error: Failed to add firewall rule. Unable to detect client IP Address. Error: There was a error when attempting to execute the process 'sqlcmd'. This may indicate the process failed to start. Error: spawn sqlcmd ENOENT."_**

**Comment by AlfredyToro** [comment]
no. I only have the task of downloading the build job artifact, then azure login and finally this sql-deploy action.
my runner is linux and I only use it as a bridge to deploy and connect to my Azure resources.

It works perfect for deploying to webapps.

**Comment by dzsquared** [comment]
No problem, we can get you up and running!
The task has 2 prerequisites for self-hosted runners:
1. sqlcmd in mssql-tools: https://docs.microsoft.com/sql/linux/sql-server-linux-setup-tools
2. sqlpackage: https://docs.microsoft.com/sql/tools/sqlpackage/sqlpackage-download

> An evergreen link (https://aka.ms/sqlpackage-linux) is available that points to the current version of sqlpackage for [Linux .NET Core](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15#get-sqlpackage-net-core-for-linux), which can be used in automating environments with the latest sqlpackage.

**Comment by dzsquared** [comment]
Please feel free to respond with more questions/info and we can reopen the issue.

**Comment by AndrewEverywhere** [comment]
we have the same issue of deploying from a self-host-runner to a Azure SQL database through private endpoint only.  "public access" is disabled in database. 

 could you elaborate the solution?  will sql-action work after sqlcmd and sqlpackage installed in SHR?
